### ISSUE TITLE
Install the plugin / Updates ?

### ISSUE THREAD

**Issue by Googinot** [TarasAutomation/cypress-telegram-reporter#1]
I really liked the idea. But it didn't work :(
I created a file with the **.env** extension and added the following lines to it: 
```
BOT_TOKEN="123"
CHAT_ID="123"
```
I figured out getting the ID, but not adding lines to the plugins. What am I doing wrong?
![Снимок экрана 2022-09-08 235149](https://user-images.githubusercontent.com/93269843/189183122-4db4835a-7f6c-4ab4-bab3-2718708a3d12.jpg)

Should we expect an update for Cypress 10+?

**Comment by TarasAutomation** [comment]
Hi!
Have you tried installing the prerequisites for the reporter?
    npm install cypress-multi-reporters --save-dev
    npm install mochawesome --save-dev
    npm install mochawesome-merge --save-dev
    npm install mochawesome-report-generator --save-dev

чт, 8 вер. 2022 р. о 20:08 Arkadiy Safronov ***@***.***> пише:

**Comment by Googinot** [comment]
Привет. Разобрался. В строке у _telegramReport**er**_ - er не хватало в окончании.
```
const telegramReporter = require('cypress-telegram-reporter');
```
